### PR TITLE
More formatting and showing code

### PR DESCRIPTION
**Pull request by steffilazerte**
Hi Danielle,
Of course I forgot to push the last set of edits I had yesterday, so they're the first commit here.

As for showing code output, I do really think that it can help. Especially because it helps you double check that the code does what it should, but also helps students see what they're supposed to be getting. If you're concerned about too many warnings, etc. we can hide those (I hid date formatting warnings in chapter 6, for example).

Here I will include some examples and you can let me know what you think.

### CODE REVIEW

**Comment by steffilazerte** [comment]
In [Chapter 6](https://github.com/DMEthier/NatureCounts_IntroTutorial/blob/9e143cbbe88bb4ce41095ad06e5224847cd121b1/06-VisualData.Rmd#L55) you show the students how to create a summary data set in order to create the point range plot. Did you know that you could do that directly with `stat_summary()`? I only say this in case you wanted to simplify the example, but it's never a bad thing for students to learn how to summarize!
```
ggplot(data = GRCA, aes(x = survey_year, y = ObservationCount)) +  
  stat_summary(fun.data = "mean_se")
```

**Comment by steffilazerte** [comment]
Also, for future reference, code chunks (stuff inbetween \`\`\`{r} and ```) don't all have to be named. A name is only required when you want to do something with that name (i.e. save a figure, reference the chunk, etc.)

**Comment by steffilazerte** [comment]
Unfortunately "hiding" the code answers isn't easy to implement in bookdown. However, I think it would be really helpful to the students (and you, so you don't have to update the answers by hand if the data base changes), to create another chapter that contains Exercise Answers. Then you can list the question and show the code and output required to get the answer.

**Comment by steffilazerte** [comment]
I've pushed all the code related changes so we're good for you to check it out. I also updated the book and hosted it on my github page (the way you will, presumably), so you can preview how the changes will actually look: https://steffilazerte.github.io/NatureCounts_IntroTutorial

**Comment by DMEthier** [comment]
This has been immensely helpful. Thank you!

**Pull request merged**
